let Strings ={
    sv:{
        "Logga in" : "Logga in",
        "Registrera" : "Registrera",
        "Spela Trailer" : "Spela Trailer",
        "SkaSpelas" : "Kommande visningar",
        "RedanSpelade" : "Redan visade filmer denna termin",
        "Styrelsen" : "Styrelsen",
        "Ordförande" : "Ordförande",
        "Sekreterare" : "Sekreterare",
        "Kassör" : "Kassör",
        "Event" : "Event",
        "Filmansvarig" : "Filmansvarig",
        "Marknadsföring" : "Marknadsföring",
        "Webb" : "Webb",
        "Fel lösenord eller email." : "Fel lösenord eller email.",
        "Lösenordet behöver minst 8 karaktärer": "Lösenordet behöver minst 8 karaktärer",
        "Lösenordet måste innehålla minst en siffra" : "Lösenordet måste innehålla minst en siffra",
        "Lösenordet måste innehålla minst en stor bokstav" : "Lösenordet måste innehålla minst en stor bokstav",
        "Lösenordet måste innehålla minst en liten bokstav" : "Lösenordet måste innehålla minst en liten bokstav",
        "Fyll i hela formuläret" : "Fyll i hela formuläret",
        "Förnamn" : "Förnamn",
        "Efternamn" : "Efternamn",
        "Ange en korrekt email" : "Ange en korrekt email",
        "Kårmedlemskap" : "Kårmedlemskap",
        "ingen (men är student)"  : "ingen (men är student)" ,
        "Ej student" : "Ej student",
        "Lösenordet matchar inte!" : "Lösenordet matchar inte!",
        "Nästa" : "Nästa",
        "Logga in" : "Logga in",
        "Startsida" : "Startsida",
        "Skapa konto" : "Skapa konto",
        "Personnummer" : "Personnummer",
        "Adress" : "Adress",
        "Postnummer" : "Postnummer",
        "Stad" : "Stad",
        "Kön: " : "Kön: ",
        "Kvinna" : "Kvinna",
        "Man" :"Man",
        "icke binär":"icke binär",
        "Telefonnummer" : "Telefonnummer",
        "Föregående" : "Föregående",
        "Registrera" : "Registrera",
        "Lösenord" : "Lösenord",
        "Upprepa Lösenord" : "Upprepa Lösenord",
        "Fel lösenord eller email." : "Fel lösenord eller email.",
        "Logga in" :"Logga in",
        "Lösenord" : "Lösenord",
        "Logga ut" : "Logga ut",
        "BeskrivFilm1" : "On Christmas Eve, three homeless people living on the streets of Tokyo discover a newborn baby among the trash and set out to find its parents..",
        "BeskrivFilm2" : "The chronicles of four years in the life of Julie, a young woman who navigates the troubled waters of her love life and struggles to find her career path, leading her to take a realistic look at who she really is.",
        "BeskrivFilm3" : "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
        "BeskrivFilm4" : "A family determined to get their young daughter into the finals of a beauty pageant take a cross-country trip in their VW bus.",
        "BeskrivFilm5" : "A teacher lives a lonely life, all the while struggling over his son's custody. His life slowly gets better as he finds love and receives good news from his son, but his new luck is about to be brutally shattered by an innocent little lie.",
        "BeskrivFilm6" : "Every semester we make your wish come true!",
        "BeskrivFilm7" : "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: 'Rosebud.'",
        "BeskrivFilm8" : "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
        "MedlemmarnasVal" : "Medlemmarnas val",
    },
    en:{
        "Logga in" : "Log in",
        "Registrera" : "Register",
        "Spela Trailer" : "Play Trailer",
        "SkaSpelas" : "Upcoming screenings",
        "RedanSpelade" : "Already shown movies this semester",
        "Styrelsen" : "The Board",
        "Ordförande" : "President",
        "Sekreterare" : "Secretary",
        "Kassör" : "Treasurer",
        "Event" : "Event",
        "Filmansvarig" : "Film Supervisor",
        "Marknadsföring" : "Marketing",
        "Webb" : "Web",
        "Fel lösenord eller email." : "Wrong password or email.",
        "Lösenordet behöver minst 8 karaktärer" : "The password needs atleast 8 characters",
        "Lösenordet måste innehålla minst en siffra" : "The password has to include atleast one number",
        "Lösenordet måste innehålla minst en stor bokstav" : "The password has to include atleast one capital letter",
        "Lösenordet måste innehålla minst en liten bokstav" : "The password has to include atleast one lowercase letter",
        "Fyll i hela formuläret" : "Fill out all the fields",
        "Förnamn" : "First name",
        "Efternamn" : "Surname",
        "Ange en korrekt email" : "Enter a valid email",
        "Kårmedlemskap" : "Student Union Membership",
        "ingen (men är student)" : "none (but am a student)",
        "Ej student" : "Not a student",
        "Lösenordet matchar inte!" : "The password doesn't match",
        "Nästa" : "Next",
        "Logga in" : "Log in",
        "Startsida" : "Homepage",
        "Skapa konto" : "Create account",
        "Personnummer" : "Personalnumber",
        "Adress" : "Address",
        "Postnummer" : "Zip code",
        "Stad" : "City",
        "Kön: " : "Gender: ",
        "Kvinna" : "Woman",
        "Man" : "Man",
        "icke binär":"Non-binary",
        "Telefonnummer" : "Phonenumber",
        "Föregående" : "Previous",
        "Registrera" : "Register",
        "Lösenord" : "Password",
        "Upprepa Lösenord" : "Repeat password",
        "Fel lösenord eller email." : "Wrong password or email.",
        "Logga in": "Log in",
        "Lösenord" : "Password",
        "Logga ut" : "Log out",
        "BeskrivFilm1" : "On Christmas Eve, three homeless people living on the streets of Tokyo discover a newborn baby among the trash and set out to find its parents..",
        "BeskrivFilm2" : "The chronicles of four years in the life of Julie, a young woman who navigates the troubled waters of her love life and struggles to find her career path, leading her to take a realistic look at who she really is.",
        "BeskrivFilm3" : "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.",
        "BeskrivFilm4" : "A family determined to get their young daughter into the finals of a beauty pageant take a cross-country trip in their VW bus.",
        "BeskrivFilm5" : "A teacher lives a lonely life, all the while struggling over his son's custody. His life slowly gets better as he finds love and receives good news from his son, but his new luck is about to be brutally shattered by an innocent little lie.",
        "BeskrivFilm6" : "Every semester we make your wish come true!",
        "BeskrivFilm7" : "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: 'Rosebud.'",
        "BeskrivFilm8" : "A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
        "MedlemmarnasVal" : "Members' choice",
    },

}
var Lang = "sv";
if(localStorage.getItem("Language") != null){
    Lang = localStorage.getItem("Language");
}

export function translate(S){
    if(Lang == "sv" ){
        return Strings.sv[S];
    }
    else{
        return Strings.en[S]
    }
}
export function changeLang(L){
    Lang = L;
    localStorage.setItem("Language", L);
    window.location.reload();
}
