let Strings ={
    sv:{
        "Logga in" : "Logga in",
        "Registrera" : "Registrera",
        "Spela Trailer" : "Spela Trailer",
        "SkaSpelas" : "Kommande visningar",
        "RedanSpelade" : "Redan visade filmer denna termin",
        "Styrelsen" : "Styrelsen",
        "Ordförande" : "Ordförande",
        "Sekreterare" : "Sekreterare",
        "Kassör" : "Kassör",
        "Event" : "Event",
        "Filmansvarig" : "Filmansvarig",
        "Marknadsföring" : "Marknadsföring",
        "Webb" : "Webb",
        "Fel lösenord eller email." : "Fel lösenord eller email.",
        "Lösenordet behöver minst 8 karaktärer": "Lösenordet behöver minst 8 karaktärer",
        "Lösenordet måste innehålla minst en siffra" : "Lösenordet måste innehålla minst en siffra",
        "Lösenordet måste innehålla minst en stor bokstav" : "Lösenordet måste innehålla minst en stor bokstav",
        "Lösenordet måste innehålla minst en liten bokstav" : "Lösenordet måste innehålla minst en liten bokstav",
        "Fyll i hela formuläret" : "Fyll i hela formuläret",
        "Förnamn" : "Förnamn",
        "Efternamn" : "Efternamn",
        "Ange en korrekt email" : "Ange en korrekt email",
        "Kårmedlemskap" : "Kårmedlemskap",
        "ingen (men är student)"  : "ingen (men är student)" ,
        "Ej student" : "Ej student",
        "Lösenordet matchar inte!" : "Lösenordet matchar inte!",
        "Nästa" : "Nästa",
        "Logga in" : "Logga in",
        "Startsida" : "Startsida",
        "Skapa konto" : "Skapa konto",
        "Personnummer" : "Personnummer",
        "Adress" : "Adress",
        "Postnummer" : "Postnummer",
        "Stad" : "Stad",
        "Kön: " : "Kön: ",
        "Kvinna" : "Kvinna",
        "Man" :"Man",
        "icke binär":"icke binär",
        "Telefonnummer" : "Telefonnummer",
        "Föregående" : "Föregående",
        "Registrera" : "Registrera",
        "Lösenord" : "Lösenord",
        "Upprepa Lösenord" : "Upprepa Lösenord",
        "Fel lösenord eller email." : "Fel lösenord eller email.",
        "Logga in" :"Logga in",
        "Lösenord" : "Lösenord",
        "Logga ut" : "Logga ut",
        "BeskrivFilm1" : "Wes Andersons mästerverk från 2014 i vilken vi kan följa Gustave H. och hans nyfunna bundsförvant Zero på deras äventyr.",
        "BeskrivFilm2" : "Under det amerikanska inbördeskriget bildar en mystisk främling, Joe , och en mexikansk fredlös, Tuco, ett oroligt partnerskap",
        "BeskrivFilm3" : "Unge Salvatore Di Vita upptäcker den perfekta flykten från livet i sin krigshärjade sicilianska by: filmhuset Cinema Paradiso, där projektionisten Alfredo ingjuter en djup kärlek till filmer i pojken.",
        "BeskrivFilm4" : "På grund av sina excentriska vanor och förbryllande konstiga filmer är regissören Ed Wood en utstött Hollywood. Ändå, med hjälp av den berömda Bela Lugosi och en hängiven besättning av missanpassade show-business-människor som tror på Eds unika vision, kan filmskaparen föra sina överdimensionerade drömmar till liv.",
        "BeskrivFilm5" : "Ultra Violence.",
        "BeskrivFilm6" : "'Tis shite being scottish.",
        "BeskrivFilm7" : "Varje termin uppfyller vi er önskning! Denna termin är denna, Everything Everywhere All at Once från 2022.",
        "BeskrivFilm8" : "Kill white folks and they pay you for it? What’s not to like?",
        "MedlemmarnasVal" : "Medlemmarnas val",
    },
    en:{
        "Logga in" : "Log in",
        "Registrera" : "Register",
        "Spela Trailer" : "Play Trailer",
        "SkaSpelas" : "Upcoming screenings",
        "RedanSpelade" : "Already shown movies this semester",
        "Styrelsen" : "The Board",
        "Ordförande" : "President",
        "Sekreterare" : "Secretary",
        "Kassör" : "Treasurer",
        "Event" : "Event",
        "Filmansvarig" : "Film Supervisor",
        "Marknadsföring" : "Marketing",
        "Webb" : "Web",
        "Fel lösenord eller email." : "Wrong password or email.",
        "Lösenordet behöver minst 8 karaktärer" : "The password needs atleast 8 characters",
        "Lösenordet måste innehålla minst en siffra" : "The password has to include atleast one number",
        "Lösenordet måste innehålla minst en stor bokstav" : "The password has to include atleast one capital letter",
        "Lösenordet måste innehålla minst en liten bokstav" : "The password has to include atleast one lowercase letter",
        "Fyll i hela formuläret" : "Fill out all the fields",
        "Förnamn" : "First name",
        "Efternamn" : "Surname",
        "Ange en korrekt email" : "Enter a valid email",
        "Kårmedlemskap" : "Student Union Membership",
        "ingen (men är student)" : "none (but am a student)",
        "Ej student" : "Not a student",
        "Lösenordet matchar inte!" : "The password doesn't match",
        "Nästa" : "Next",
        "Logga in" : "Log in",
        "Startsida" : "Homepage",
        "Skapa konto" : "Create account",
        "Personnummer" : "Personalnumber",
        "Adress" : "Address",
        "Postnummer" : "Zip code",
        "Stad" : "City",
        "Kön: " : "Gender: ",
        "Kvinna" : "Woman",
        "Man" : "Man",
        "icke binär":"Non-binary",
        "Telefonnummer" : "Phonenumber",
        "Föregående" : "Previous",
        "Registrera" : "Register",
        "Lösenord" : "Password",
        "Upprepa Lösenord" : "Repeat password",
        "Fel lösenord eller email." : "Wrong password or email.",
        "Logga in": "Log in",
        "Lösenord" : "Password",
        "Logga ut" : "Log out",
        "BeskrivFilm1" : "Wes Anderson's masterpiece from 2014 in which we can follow Gustave H. and his newfound ally Zero on their adventures.",
        "BeskrivFilm2" : "During the Civil War, a mysterious stranger, Joe, and a Mexican outlaw, Tuco, form an uneasy partnership",
        "BeskrivFilm3" : "Young Salvatore Di Vita discovers the perfect escape from life in his war-torn Sicilian village: the Cinema Paradiso movie house, where projectionist Alfredo instills in the boy a deep love of films.",
        "BeskrivFilm4" : "Because of his eccentric habits and bafflingly strange films, director Ed Wood  is a Hollywood outcast. Nevertheless, with the help of the formerly famous Bela Lugosi and a devoted cast and crew of show-business misfits who believe in Ed's off-kilter vision, the filmmaker is able to bring his oversize dreams to cinematic life.",
        "BeskrivFilm5" : "Ultra Violence ;).",
        "BeskrivFilm6" : "'Tis shite being scottish'.",
        "BeskrivFilm7" : "Every semester we make your wish come true! This years entry is Everything Everywhere All at Once from 2022.",
        "BeskrivFilm8" : "Kill white folks and they pay you for it? What’s not to like?”",
        "MedlemmarnasVal" : "Members' choice",
    },

}
var Lang = "sv";
if(localStorage.getItem("Language") != null){
    Lang = localStorage.getItem("Language");
}

export function translate(S){
    if(Lang == "sv" ){
        return Strings.sv[S];
    }
    else{
        return Strings.en[S]
    }
}
export function changeLang(L){
    Lang = L;
    localStorage.setItem("Language", L);
    window.location.reload();
}
